create table mde_empresas (emp_activa BOOLEAN DEFAULT FALSE, emp_id integer not null auto_increment, emp_cuit varchar(13) not null, emp_correo varchar(30) not null, emp_telefono varchar(30) not null, emp_domic_legal varchar(50) not null, emp_razon varchar(60) not null, primary key (emp_id)) engine=InnoDB;
create table mde_habilitacion_docs (hdo_adjunto_fecha date not null, hdo_adjunto_orden integer not null, hdo_eha_id integer not null, hdo_id integer not null auto_increment, hdo_rev_id integer not null, hdo_tad_id integer not null, primary key (hdo_id)) engine=InnoDB;
create table mde_inmuebles_personas (ipe_es_admin_edif BOOLEAN DEFAULT FALSE, ipe_es_coprop_edif BOOLEAN DEFAULT FALSE, ipe_id integer not null auto_increment, ipe_inm_id integer not null, ipe_per_id integer not null, primary key (ipe_id)) engine=InnoDB;
create table mde_personas (per_activa BOOLEAN DEFAULT FALSE, per_es_admin_edif BOOLEAN DEFAULT FALSE, per_es_coprop_edif BOOLEAN DEFAULT FALSE, per_es_dueno_emp BOOLEAN DEFAULT FALSE, per_es_reptec_emp BOOLEAN DEFAULT FALSE, per_id integer not null auto_increment, per_tipodoc integer not null, per_numdoc varchar(8) not null, per_telefono varchar(12) not null, per_correo varchar(40) not null, per_nombre varchar(50) not null, primary key (per_id)) engine=InnoDB;
alter table mde_habilitacion_docs add constraint UK_kk4du88yo4iwvdhk94kpvxua1 unique (hdo_eha_id);
alter table mde_habilitacion_docs add constraint UK_m9ffnv9doqunp216af38cd749 unique (hdo_rev_id);
alter table mde_habilitacion_docs add constraint UK_lg8j2cp1o8dm9jl60h29fu3ym unique (hdo_tad_id);
alter table mde_inmuebles_personas add constraint UK_bxtka2ajk5uinypyhakk2ba2p unique (ipe_inm_id);
alter table mde_inmuebles_personas add constraint UK_2a3y079v96xlh92v45s23x3q0 unique (ipe_per_id);
create table mde_destinos (dst_activo BOOLEAN DEFAULT FALSE, dst_codigo varchar(3) not null, dst_id integer not null auto_increment, dst_detalle varchar(40), primary key (dst_id)) engine=InnoDB;
create table mde_distrito (dis_activo BOOLEAN DEFAULT FALSE, dis_codigo varchar(2) not null, dis_id integer not null auto_increment, dis_nombre varchar(30) not null, primary key (dis_id)) engine=InnoDB;
create table mde_empresas_habilitacion (eha_emp_id integer not null, eha_fecha date not null, eha_habilitada BOOLEAN DEFAULT FALSE, eha_id integer not null auto_increment, eha_rev_id integer not null, eha_vto_hab date not null, eha_expediente varchar(20) not null, primary key (eha_id)) engine=InnoDB;
create table mde_empresas_personas (epe_emp_id integer not null, epe_es_dueno_emp BOOLEAN DEFAULT FALSE, epe_es_reptec_emp BOOLEAN DEFAULT FALSE, epe_id integer not null auto_increment, epe_per_id integer not null, primary key (epe_id)) engine=InnoDB;
create table mde_inmuebles (inm_activo BOOLEAN DEFAULT FALSE, inm_cod_postal varchar(4) not null, inm_dst_id integer not null, inm_id integer not null auto_increment, inm_padron integer not null, inm_dirección varchar(30) not null, primary key (inm_id)) engine=InnoDB;
create table mde_inmuebles_medioselevacion (ime_id integer not null auto_increment, ime_inm_id integer not null, ime_mde_id integer not null, primary key (ime_id)) engine=InnoDB;
create table mde_medios_docs (mdo_adjunto_fecha date not null, mdo_adjunto_orden integer not null, mdo_id integer not null auto_increment, mdo_mha_id integer not null, mdo_rev_id integer not null, mdo_tad_id integer not null, primary key (mdo_id)) engine=InnoDB;
create table mde_medios_habilitacion (mha_emp_id integer not null, mha_fecha date not null, mha_fecha_inspec date not null, mha_fecha_pago date not null, mha_fecha_vto date not null, mha_habilitado BOOLEAN DEFAULT FALSE, mha_id integer not null auto_increment, mha_oblea_entregada BOOLEAN DEFAULT FALSE, mha_per_id integer not null, mha_planos_aprob BOOLEAN DEFAULT FALSE, mha_rev_id integer not null, mha_vto_hab date not null, mha_expediente varchar(20) not null, primary key (mha_id)) engine=InnoDB;
create table mde_medioselevacion (mde_activo BOOLEAN DEFAULT FALSE, mde_id integer not null auto_increment, mde_niveles integer not null, mde_tma_id integer not null, mde_tipo varchar(25) not null, mde_ubicacion varchar(30) not null, primary key (mde_id)) engine=InnoDB;
create table mde_revisores (rev_activo BOOLEAN DEFAULT FALSE, rev_aprob_emp BOOLEAN DEFAULT FALSE, rev_aprob_mde BOOLEAN DEFAULT FALSE, rev_id integer not null auto_increment, rev_renov_mde BOOLEAN DEFAULT FALSE, rev_numdoc varchar(8) not null, rev_nombre varchar(50) not null, primary key (rev_id)) engine=InnoDB;
create table mde_tipos_adjuntos (tad_activo BOOLEAN DEFAULT FALSE, tad_cod integer not null, tad_id integer not null auto_increment, tad_nombre varchar(30) not null, primary key (tad_id)) engine=InnoDB;
create table mde_tipos_maquinas (tma_activa BOOLEAN DEFAULT FALSE, tma_cod integer not null, tma_id integer not null auto_increment, tma_detalle varchar(30), primary key (tma_id)) engine=InnoDB;
alter table mde_empresas_habilitacion add constraint UK_mclvjcavrjy29df0xdbo7mb3m unique (eha_emp_id);
alter table mde_empresas_habilitacion add constraint UK_y6fm9vw1hwecg0ylfcuqr49m unique (eha_rev_id);
alter table mde_empresas_personas add constraint UK_9hrw5jgvhlbd2fiygeoxdfhuv unique (epe_emp_id);
alter table mde_empresas_personas add constraint UK_iyqn86sk5by0oi0vkeer76dnn unique (epe_per_id);
alter table mde_inmuebles add constraint UK_gn3oka4p7j676sagp37u2mwvs unique (inm_dst_id);
alter table mde_inmuebles_medioselevacion add constraint UK_r0td1cqjtskf1dp9xldnit4yf unique (ime_inm_id);
alter table mde_inmuebles_medioselevacion add constraint UK_hp4usxsuene6dkqcnjwcgiegt unique (ime_mde_id);
alter table mde_medios_docs add constraint UK_rfs2ta7hcef4pfp7pok34uwsh unique (mdo_mha_id);
alter table mde_medios_docs add constraint UK_nfrk481wknssi6icn7m5rtv6p unique (mdo_rev_id);
alter table mde_medios_docs add constraint UK_damypbatt0qpehda9u6cuid4l unique (mdo_tad_id);
alter table mde_medios_habilitacion add constraint UK_m9dpqr8diijfjiudxj23w3311 unique (mha_emp_id);
alter table mde_medios_habilitacion add constraint UK_6qkfucs49inqknh12cfq43uo0 unique (mha_per_id);
alter table mde_medios_habilitacion add constraint UK_3dfrpxxoku0fxt6ban2oq37um unique (mha_rev_id);
alter table mde_medioselevacion add constraint UK_hl3uo04wh8cfhl8l6mselmaoy unique (mde_tma_id);
alter table mde_habilitacion_docs add constraint FKrgmannfbl4gu082crp8kccxix foreign key (hdo_eha_id) references mde_empresas_habilitacion (eha_id);
alter table mde_habilitacion_docs add constraint FKnpcdvoum1hy1i0h1nla922gq2 foreign key (hdo_rev_id) references mde_revisores (rev_id);
alter table mde_habilitacion_docs add constraint FKfd1lub7u9rwfgj9i9k3lvn6ow foreign key (hdo_tad_id) references mde_tipos_adjuntos (tad_id);
alter table mde_inmuebles_personas add constraint FKl942u7em9xgm1dgqirvyjsqky foreign key (ipe_inm_id) references mde_inmuebles (inm_id);
alter table mde_inmuebles_personas add constraint FK4tkmyr4wjb1yxiumxsrdr4lkq foreign key (ipe_per_id) references mde_personas (per_id);
alter table mde_empresas_habilitacion add constraint FKdy6waynokn6rdgyl7m1m7gxnj foreign key (eha_emp_id) references mde_empresas (emp_id);
alter table mde_empresas_habilitacion add constraint FKfl4l6yaus3h5prtaw1u38mwp8 foreign key (eha_rev_id) references mde_revisores (rev_id);
alter table mde_empresas_personas add constraint FKsb49rjd4ljaby99p8pcfhti7x foreign key (epe_emp_id) references mde_empresas (emp_id);
alter table mde_empresas_personas add constraint FKck2sdu2805env1lo17iatkrcf foreign key (epe_per_id) references mde_personas (per_id);
alter table mde_inmuebles add constraint FK1u5fbpw0o0tugum73j5d21rv8 foreign key (inm_dst_id) references mde_destinos (dst_id);
alter table mde_inmuebles_medioselevacion add constraint FKhf0b8w108f2rveya7tgej8ugs foreign key (ime_inm_id) references mde_inmuebles (inm_id);
alter table mde_inmuebles_medioselevacion add constraint FKjv4edw0t5k61pj0ji2es9h2kd foreign key (ime_mde_id) references mde_medioselevacion (mde_id);
alter table mde_medios_docs add constraint FK73i2ct9iqta1ekq20crh2wqy5 foreign key (mdo_mha_id) references mde_medios_habilitacion (mha_id);
alter table mde_medios_docs add constraint FK3aj1w1mgxodxha7xfpxrmvihh foreign key (mdo_rev_id) references mde_revisores (rev_id);
alter table mde_medios_docs add constraint FK28h4skjw49sw2gwv872tmrjh9 foreign key (mdo_tad_id) references mde_tipos_adjuntos (tad_id);
alter table mde_medios_habilitacion add constraint FK1tnjg0d056d5yma4rpqcbyy86 foreign key (mha_emp_id) references mde_empresas (emp_id);
alter table mde_medios_habilitacion add constraint FK58hp4wcfvjauvfqf6chbx6ri4 foreign key (mha_per_id) references mde_personas (per_id);
alter table mde_medios_habilitacion add constraint FKfgev9qjhg2wfw7pdsve41d8u5 foreign key (mha_rev_id) references mde_revisores (rev_id);
alter table mde_medioselevacion add constraint FKap03rlxdn9yqetxgqveegnt8n foreign key (mde_tma_id) references mde_tipos_maquinas (tma_id);
